---
- hosts: localhost
  connection: local
  gather_facts: yes

  roles:
    - role: aws-deploy
      tags: aws-vm
      vars:
        key: "AnsibleTower"
        size: "t2.medium"
        image: "ami-096cb92bb3580c759"
        region: "eu-west-2"
        group: K8s
        wait: yes

- name: Configure K8s host
  hosts: master:worker
  become: yes
  vars:
    ansible_user: ubuntu
    platform: aws
  
  roles:
    - role: provision-k8s
