---
- hosts: localhost
  connection: local
#  collections:
#   - community.digitalocean

  roles:
    - role: aws-deploy
      vars:
        key: "AnsibleTower"
        size: "t2.medium"
        image: "ami-096cb92bb3580c759"
        #aws_access_key:  "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
        #aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
        region: "eu-west-2"
        group: K8s
        wait: yes

- name: Configure K8s host
  hosts: master:worker
  become: yes
  vars:
    ansible_user: ubuntu
  
  roles:
    - role: provision-k8s
