---
- hosts: localhost
  connection: local
  gather_facts: yes
  tasks:
  - name: test community.aws
    community.aws.ec2_instance:
      name: "{{hostvars[item].inventory_hostname}}"
      state: absent
      #network:
      #  assign_public_ip: true
    with_inventory_hostnames:
    - master
    - worker
