- hosts: localhost 
  connection: local
  gather_facts: yes
  vars:
     # Turn our passed env variables into something ansible can use to talk to azure
    client_id: "{{ lookup('env','AZURE_CLIENT_ID') }}"
    secret: "{{ lookup('env','AZURE_SECRET') }}"
    tenant_id: "{{ lookup('env','AZURE_TENANT') }}"
    azure_clients_object_id: "{{ lookup('env','AZURE_CLIENTS_OBJECT_ID') }}" #TEMP - should figure this out at runtime
    subscription_id: "{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}"

    # Where to deploy our resources by default
    location: "northeurope"
  tasks:
  #- name: Create Resource Group
  #  azure.azcollection.azure_rm_resourcegroup:
  #    subscription_id: "{{ subscription_id }}"
  #    client_id: "{{ client_id }}"
  #    secret: "{{ secret }}"
  #    tenant: "{{ tenant_id }}"
  #    location: "{{ location }}"
  #    name: "{{ resource_group_name }}"
  #    #state: absent
  - name: Create VM with defaults
    azure_rm_virtualmachine:
     resource_group: ansible
     name: "{{hostvars[item].inventory_hostname}}"
     admin_username: ansible
     admin_password: pa$$w0rd
     vm_size: Standard_B2s
     ssh_public_keys:
     - path: "/home/ansible/.ssh/authorized_keys"
       key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDs/7Xo7zs/b2iA+5b2eN6QSOevw1tmN1ghUu70ZM+cJoJ8rCcxziuj7v3Hl/PAUMT8Eo0NSVqsMGoHHmpWTUUnuiXvxjV6u4nHOIbFA4MYqSOIxG0SZOTVSX2d7mYSTGPzcZomRzpSL0iTe4PAuUqcnQ9Cvo4K+eaM+9WsSsjex7rZUOQIcP02aKcOgAgp5vEX0TV7MBZcSfeo8exxszaUo1q3EgUCnEOokylHrjB6DTWea3ivzatYp2k8GZlIxO/Rz4AYm3b0RuusqUF09nNuy4Bkr1vjJPa241SwOoS2bCrIY34x9zWxGzm7022Udzl2KewSor4Z/sSjTIP1qNnj root@ansibletower
     image:
       offer: 0001-com-ubuntu-server-focal 
       publisher: Canonical
       sku: '20_04-lts'
       version: 20.04.202105030
    with_inventory_hostnames:
      - master
      - worker
    register: instances_info

  - name: debug instances
    debug:
      msg: "This is the name {{item.ansible_facts.azure_vm.name}} This is the Public IP {{item.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress}}"
     # msg: "This is the NAME: {{item.name}}, This is the IP: {{item.networkInterfaces[0].accessConfigs[0].natIP}}"
    loop: "{{instances_info.results}}"
