---
- hosts: localhost
  connection: local
  collections:
    - community.digitalocean

  roles:
    # this main.yml in this roles task folder can be altered to use the standard module
    # rather than a collection
    - role: deploy-using-tower
      vars:
        image: ubuntu-20-10-x64
        region: lon1
        size: s-1vcpu-1gb
        state: present
        key: 29424620
        server: ansible-5
