---
- hosts: localhost
  connection: local
  collections:
    - community.digitalocean

  roles:
    - role: deploy-using-collection
      vars:
        image: ubuntu-20-10-x64
        region: lon1
        size: s-1vcpu-1gb
        state: present
        key: 29424620
        #server: ansible-5
