---
- name: Configure K8s host
  hosts: master:worker
  vars:
          #ansible_ssh_user: root
          ### don't work######ansible_ssh_private_key_file: "{{ lookup('file','~/.ssh/id_rsa') }}"
          #workes##### ansible_ssh_private_key_file: "~/.ssh/id_rsa"
  
  roles:
    - role: provision-k8s
  #tasks:
  #- name: Collect only facts returned by facter
  #  setup:
  #  register: setup
  #  tags: setup
  #- name: debug output of facts
  #  debug:
  #    var: setup
