---
- hosts: localhost
  connection: local
  collections:
    - community.digitalocean

  roles:
    - role: deploy-using-tower
      vars:
        image: ubuntu-20-10-x64
        region: lon1
        size: s-1vcpu-1gb
        state: present
        key: 29424620
        server: ansible-5

- name: check setup
  hosts: just_created
  vars:
          #ansible_ssh_user: root
          ### don't work######ansible_ssh_private_key_file: "{{ lookup('file','~/.ssh/id_rsa') }}"
          #workes##### ansible_ssh_private_key_file: "~/.ssh/id_rsa"
  
  tasks:
  - name: Collect only facts returned by facter
    setup:
    tags: setup

