- name: Create IP address
  hosts: localhost
  gather_facts: no

  roles:
    - role: gcp-deploy
      vars:
         machine_type: "n1-standard-1"
         zone: "us-west1-a"
         state: "present"

- name: Configure K8s host
  hosts: master:worker
  vars:
    ansible_ssh_private_key_file: "/root/.ssh/google_compute_engine" # NOT SURE IF NEEDED
  tasks:
    - name: setup bash completion
      apt:
        name: bash-completion
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

- name: Configure K8s host
  hosts: master:worker
  vars:
          #ansible_ssh_user: root
          ### don't work######ansible_ssh_private_key_file: "{{ lookup('file','~/.ssh/id_rsa') }}"
          #workes##### ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_ssh_private_key_file: "/root/.ssh/google_compute_engine" # NOT SURE IF NEEDED

  roles:
    - role: provision-k8s

