---
# tasks file for roles/azure-deploy
  - name: Create VM with defaults
    azure.azcollection.azure_rm_virtualmachine:
     resource_group: ansible
     name: "{{hostvars[item].inventory_hostname}}"
     admin_username: ansible
     ssh_password_enabled: false
     #admin_password: pa$$w0rd
     vm_size: Standard_B2s
     ssh_public_keys:
     - path: "/home/ansible/.ssh/authorized_keys"
       key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDs/7Xo7zs/b2iA+5b2eN6QSOevw1tmN1ghUu70ZM+cJoJ8rCcxziuj7v3Hl/PAUMT8Eo0NSVqsMGoHHmpWTUUnuiXvxjV6u4nHOIbFA4MYqSOIxG0SZOTVSX2d7mYSTGPzcZomRzpSL0iTe4PAuUqcnQ9Cvo4K+eaM+9WsSsjex7rZUOQIcP02aKcOgAgp5vEX0TV7MBZcSfeo8exxszaUo1q3EgUCnEOokylHrjB6DTWea3ivzatYp2k8GZlIxO/Rz4AYm3b0RuusqUF09nNuy4Bkr1vjJPa241SwOoS2bCrIY34x9zWxGzm7022Udzl2KewSor4Z/sSjTIP1qNnj root@ansibletower
     image:
       offer: 0001-com-ubuntu-server-focal 
       publisher: Canonical
       sku: '20_04-lts'
       version: 20.04.202105030
    with_inventory_hostnames:
      - master
      - worker
    register: instances

  - name: debug instances
    debug:
      msg: "This is the name {{item.ansible_facts.azure_vm.name}} This is the Public IP {{item.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress}}"
     # msg: "This is the NAME: {{item.name}}, This is the IP: {{item.networkInterfaces[0].accessConfigs[0].natIP}}"
    loop: "{{instances.results}}"


  - name: Wait for port 22 to become open on the host, don't start checking for 30 seconds
    wait_for:
       host: "{{item.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress}}"
       port: 22
       delay: 30
       timeout: 300
    loop: "{{ instances.results }}"

  - name: Add host to group 'master'
    add_host:
       name: "{{item.ansible_facts.azure_vm.name}}"
       ansible_ssh_host: "{{item.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress}}"
       groups: master
    when: item.ansible_facts.azure_vm.name.find("master") != -1
    loop: "{{ instances.results }}"
  - name: Add host to group 'worker'
    add_host:
       name: "{{item.ansible_facts.azure_vm.name}}"
       ansible_ssh_host:  "{{item.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress}}"
       groups: worker
    when: item.ansible_facts.azure_vm.name.find("master") == -1
    loop: "{{ instances.results }}"
