---
# tasks file for roles/deploy
- name: ensure a droplet is present
  digital_ocean_droplet:
    state: "{{ state }}" #present
    name: "{{ item }}" #ansible-4
    oauth_token: "{{ token }}"
    size: "{{ size }} " #s-1vcpu-1gb 
    region: "{{ region }}" #lon1
    image: "{{ image }} " #ubuntu-16-04-x64
    ssh_keys: "{{ key }}" #29424620
    wait_timeout: 500
  with_inventory_hostnames:
    - server
  register: droplet_info
- debug:
    var: droplet_info


