---
# tasks file for roles/deploy
- name: ensure a droplet is present
  digital_ocean_droplet:
    state: present
    name: ansible-4
    oauth_token: "{{ token }}"
    size: s-1vcpu-1gb 
    region: lon1
    image: ubuntu-16-04-x64
    ssh_keys: 29424620
    wait_timeout: 500
  register: droplet_info
- debug:
    var: droplet_info


