---
# defaults file for roles/common
OS: xUbuntu_20.10 # doesn't appear to be a 20.10 for crio
CENTOS_OS: CentOS_8 
OS_1: xUbuntu_20.04 # not ideal
CRIO_VERSION: "1.20"
CENTOS_LIBCONTAINERS_REPO: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ CENTOS_OS }}/devel:kubic:libcontainers:stable.repo
CENTOS_CRIO_REPO: https://download.opensuse.org/repositories/devel:kubic:libcontainers:stable:cri-o:{{ CRIO_VERSION }}/{{ CENTOS_OS }}/devel:kubic:libcontainers:stable:cri-o:{{ CRIO_VERSION }}.repo
CENTOS_REPO_PATH: /etc/yum.repos.d/
LIBCONTAINERS_REPO: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/{{ OS }}
CRIO_REPO: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/{{ CRIO_VERSION }}/{{OS_1}}
K8S_KEY: https://packages.cloud.google.com/apt/doc/apt-key.gpg
K8S_REPO: kubernetes.list
CENTOS_K8S_REPO: kubernetes.repo
K8S_CONFIG: /etc/kubernetes/admin.conf
K8S_PACKAGES: 
  - kubelet
  - kubeadm
  - kubectl
K8S_COMP_FILE: completion.bash.inc
#calico
#CNI: https://docs.projectcalico.org/manifests/calico.yaml
#cilium
CNI: https://raw.githubusercontent.com/cilium/cilium/HEAD/install/kubernetes/quick-install.yaml
NO_TAINT: kubectl taint node "{{ ansible_hostname }}" node-role.kubernetes.io/master:NoSchedule-
APT_REPO_PATH: /etc/apt/sources.list.d/
CRIO_PACKAGE: cri-o
CRIO_PACKAGES:
   - cri-o
   - cri-o-runc
COMMON_PACKAGES:
   - curl
   - apt-transport-https
CGROUP_FILE: 02-cgroup-manager.conf
CGROUP_PATH: /etc/crio/crio.conf.d/
CRICTL_VERSION: "v1.20.0"
CRICTL_PACKAGE: https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ CRICTL_VERSION }}/crictl-{{ CRICTL_VERSION }}-linux-amd64.tar.gz
CRITEST_PACKAGE: https://github.com/kubernetes-sigs/cri-tools/releases/download/{{ CRICTL_VERSION }}/critest-{{ CRICTL_VERSION }}-linux-amd64.tar.gz
